import { useState } from 'react'
import { LanguageContext } from './language-context'

const translations = {
  en: {
    header_title: 'Dashboard',
    switch_language: 'Switch language',
    notifications: 'Notifications',
    settings: 'Settings',
    logout: 'Log out',
    staff_account: 'Staff account',
    nav_dashboard: 'Dashboard',
    nav_rooms: 'Rooms',
    nav_categories: 'Categories',
    nav_customers: 'Customers',
    nav_reservations: 'Reservations',
    nav_payments: 'Payments',
    notif_checkout_soon: 'Room 12 checkout due in 2 hours',
    notif_maintenance_done: 'Room 5 maintenance completed',
    notif_payment_received: 'Payment received for Reservation #204',
    welcome_back: 'Welcome back',
    dashboard_subtitle: "Here's what's happening across your property today.",
    stat_available: 'Available',
    stat_reserved: 'Reserved',
    stat_occupied: 'Occupied',
    stat_maintenance: 'Maintenance',
    stat_out_of_service: 'Out of Service',
    recent_reservations: 'Recent Reservations',
    quick_actions: 'Quick Actions',
    action_new_reservation: 'New Reservation',
    action_add_room: 'Add Room',
    action_add_customer: 'Add Customer',
    categories_title: 'Categories',
    categories_subtitle: 'Manage room categories, prices, and room assignments.',
    categories_add: 'Add category',
    categories_add_defaults: 'Add default categories',
    categories_total: 'Categories',
    categories_assigned_rooms: 'Assigned rooms',
    categories_default_price: 'Default price',
    categories_room: 'room',
    categories_rooms: 'rooms',
    categories_empty_title: 'No categories yet',
    categories_empty_text: 'Start with the five standard room categories or create a custom one.',
    categories_no_description: 'No description provided.',
    category_form_create_title: 'New category',
    category_form_edit_title: 'Edit category',
    category_name_label: 'English name',
    category_name_placeholder: 'Furnished apartment',
    category_description_label: 'English description',
    category_description_placeholder: 'Short description for this category',
    category_price_label: 'Default price',
    category_price_hint: 'Rooms inherit this price unless their price is changed explicitly.',
    category_create: 'Create category',
    category_save: 'Save category',
    category_cancel: 'Cancel',
    category_edit: 'Edit',
    category_delete: 'Delete',
    category_delete_title: 'Delete category',
    category_delete_intro: 'This action cannot be undone.',
    category_delete_confirm: 'Delete category',
    category_delete_blocked: 'This category contains rooms. Move or delete those rooms before deleting the category.',
    category_name_required: 'Category name is required.',
    category_loading: 'Loading categories...',
    category_error_title: 'Unable to load categories',
    category_seed_success: 'Default categories added.',
    category_seed_none: 'Default categories already exist.',
    category_create_success: 'Category created.',
    category_update_success: 'Category updated.',
    category_delete_success: 'Category deleted.',
    category_auth_required: 'Your session is not authenticated. Log in again before changing categories.',
    rooms_title: 'Rooms',
    rooms_subtitle: 'Manage building units, category pricing, availability, and operational status.',
    rooms_add: 'Add room',
    rooms_add_test: 'Add test rooms',
    rooms_total: 'Total rooms',
    rooms_available: 'Available',
    rooms_active: 'Reserved / occupied',
    rooms_attention: 'Needs attention',
    rooms_search_placeholder: 'Search room number, category, or description',
    rooms_filter_all_statuses: 'All statuses',
    rooms_filter_all_categories: 'All categories',
    rooms_no_results_title: 'No rooms found',
    rooms_no_results_text: 'Adjust your filters or create a new room.',
    rooms_empty_title: 'No rooms yet',
    rooms_empty_text: 'Create categories first, then register each room with its floor, capacity, price, and status.',
    rooms_missing_categories: 'Create at least one category before adding rooms.',
    room_form_create_title: 'New room',
    room_form_edit_title: 'Edit room',
    room_number_label: 'Room number',
    room_number_placeholder: 'A12 or 204',
    room_category_label: 'Category',
    room_description_label: 'Description',
    room_description_placeholder: 'Optional notes: balcony, private bathroom, repairs...',
    room_floor_label: 'Floor',
    room_floor_short: 'Floor',
    room_capacity_label: 'Capacity',
    room_capacity_unit: 'people',
    room_price_label: 'Price',
    room_status_label: 'Status',
    room_create: 'Create room',
    room_save: 'Save room',
    room_cancel: 'Cancel',
    room_edit: 'Edit',
    room_delete: 'Delete',
    room_delete_title: 'Delete room',
    room_delete_intro: 'This action cannot be undone.',
    room_delete_safety_note: 'If this room has reservation history, deletion will be blocked to protect business records.',
    room_delete_confirm: 'Delete room',
    room_delete_blocked: 'This room has reservation history. It cannot be deleted.',
    room_number_required: 'Room number is required.',
    room_category_required: 'Category is required.',
    room_price_invalid: 'Price must be zero or greater.',
    room_duplicate_number: 'A room with this number already exists.',
    room_loading: 'Loading rooms...',
    room_error_title: 'Unable to load rooms',
    room_create_success: 'Room created.',
    room_update_success: 'Room updated.',
    room_delete_success: 'Room deleted.',
    room_seed_success: 'Test rooms added.',
    room_seed_none: 'Test rooms already exist.',
    room_auth_required: 'Your session is not authenticated. Log in again before changing rooms.',
    room_no_category: 'No category',
    room_inherited_price: 'Inherited from category',
    room_custom_price: 'Custom room price',
    room_use_category_price: 'Use category price',
    room_floor_unknown: 'Floor not set',
    room_capacity_unknown: 'Capacity not set',
  },
  fr: {
    header_title: 'Tableau de bord',
    switch_language: 'Changer de langue',
    notifications: 'Notifications',
    settings: 'Paramètres',
    logout: 'Déconnexion',
    staff_account: 'Compte du personnel',
    nav_dashboard: 'Tableau de bord',
    nav_rooms: 'Chambres',
    nav_categories: 'Catégories',
    nav_customers: 'Clients',
    nav_reservations: 'Réservations',
    nav_payments: 'Paiements',
    notif_checkout_soon: 'Chambre 12 : départ prévu dans 2 heures',
    notif_maintenance_done: 'Chambre 5 : entretien terminé',
    notif_payment_received: 'Paiement reçu pour la réservation #204',
    welcome_back: 'Bon retour',
    dashboard_subtitle: "Voici ce qui se passe dans votre établissement aujourd'hui.",
    stat_available: 'Disponibles',
    stat_reserved: 'Réservées',
    stat_occupied: 'Occupées',
    stat_maintenance: 'Entretien',
    stat_out_of_service: 'Hors service',
    recent_reservations: 'Réservations récentes',
    quick_actions: 'Actions rapides',
    action_new_reservation: 'Nouvelle réservation',
    action_add_room: 'Ajouter une chambre',
    action_add_customer: 'Ajouter un client',
    categories_title: 'Catégories',
    categories_subtitle: 'Gérez les catégories de chambres, les prix et les affectations.',
    categories_add: 'Ajouter une catégorie',
    categories_add_defaults: 'Ajouter les catégories par défaut',
    categories_total: 'Catégories',
    categories_assigned_rooms: 'Chambres affectées',
    categories_default_price: 'Prix par défaut',
    categories_room: 'chambre',
    categories_rooms: 'chambres',
    categories_empty_title: 'Aucune catégorie',
    categories_empty_text: 'Commencez avec les cinq catégories standards ou créez une catégorie personnalisée.',
    categories_no_description: 'Aucune description renseignée.',
    category_form_create_title: 'Nouvelle catégorie',
    category_form_edit_title: 'Modifier la catégorie',
    category_name_label: 'Nom français',
    category_name_placeholder: 'Appartement meublé',
    category_description_label: 'Description française',
    category_description_placeholder: 'Courte description de cette catégorie',
    category_price_label: 'Prix par défaut',
    category_price_hint: 'Les chambres héritent de ce prix sauf modification explicite.',
    category_create: 'Créer la catégorie',
    category_save: 'Enregistrer',
    category_cancel: 'Annuler',
    category_edit: 'Modifier',
    category_delete: 'Supprimer',
    category_delete_title: 'Supprimer la catégorie',
    category_delete_intro: 'Cette action est définitive.',
    category_delete_confirm: 'Supprimer la catégorie',
    category_delete_blocked: 'Cette catégorie contient des chambres. Déplacez ou supprimez ces chambres avant de supprimer la catégorie.',
    category_name_required: 'Le nom de la catégorie est obligatoire.',
    category_loading: 'Chargement des catégories...',
    category_error_title: 'Impossible de charger les catégories',
    category_seed_success: 'Catégories par défaut ajoutées.',
    category_seed_none: 'Les catégories par défaut existent déjà.',
    category_create_success: 'Catégorie créée.',
    category_update_success: 'Catégorie mise à jour.',
    category_delete_success: 'Catégorie supprimée.',
    category_auth_required: "Votre session n'est pas authentifiée. Reconnectez-vous avant de modifier les catégories.",
    rooms_title: 'Chambres',
    rooms_subtitle: "Gérez les unités du bâtiment, les prix par catégorie, la disponibilité et l'état opérationnel.",
    rooms_add: 'Ajouter une chambre',
    rooms_add_test: 'Ajouter des chambres test',
    rooms_total: 'Total chambres',
    rooms_available: 'Disponibles',
    rooms_active: 'Réservées / occupées',
    rooms_attention: 'À surveiller',
    rooms_search_placeholder: 'Rechercher par numéro, catégorie ou description',
    rooms_filter_all_statuses: 'Tous les statuts',
    rooms_filter_all_categories: 'Toutes les catégories',
    rooms_no_results_title: 'Aucune chambre trouvée',
    rooms_no_results_text: 'Ajustez vos filtres ou créez une nouvelle chambre.',
    rooms_empty_title: 'Aucune chambre',
    rooms_empty_text: "Créez d'abord les catégories, puis enregistrez chaque chambre avec son étage, sa capacité, son prix et son statut.",
    rooms_missing_categories: "Créez au moins une catégorie avant d'ajouter des chambres.",
    room_form_create_title: 'Nouvelle chambre',
    room_form_edit_title: 'Modifier la chambre',
    room_number_label: 'Numéro de chambre',
    room_number_placeholder: 'A12 ou 204',
    room_category_label: 'Catégorie',
    room_description_label: 'Description',
    room_description_placeholder: 'Notes optionnelles : balcon, douche privée, réparations...',
    room_floor_label: 'Étage',
    room_floor_short: 'Étage',
    room_capacity_label: 'Capacité',
    room_capacity_unit: 'personnes',
    room_price_label: 'Prix',
    room_status_label: 'Statut',
    room_create: 'Créer la chambre',
    room_save: 'Enregistrer',
    room_cancel: 'Annuler',
    room_edit: 'Modifier',
    room_delete: 'Supprimer',
    room_delete_title: 'Supprimer la chambre',
    room_delete_intro: 'Cette action est définitive.',
    room_delete_safety_note: "Si cette chambre possède un historique de réservation, la suppression sera bloquée afin de protéger les données métier.",
    room_delete_confirm: 'Supprimer la chambre',
    room_delete_blocked: 'Cette chambre possède un historique de réservation. Elle ne peut pas être supprimée.',
    room_number_required: 'Le numéro de chambre est obligatoire.',
    room_category_required: 'La catégorie est obligatoire.',
    room_price_invalid: 'Le prix doit être supérieur ou égal à zéro.',
    room_duplicate_number: 'Une chambre avec ce numéro existe déjà.',
    room_loading: 'Chargement des chambres...',
    room_error_title: 'Impossible de charger les chambres',
    room_create_success: 'Chambre créée.',
    room_update_success: 'Chambre mise à jour.',
    room_delete_success: 'Chambre supprimée.',
    room_seed_success: 'Chambres test ajoutées.',
    room_seed_none: 'Les chambres test existent déjà.',
    room_auth_required: "Votre session n'est pas authentifiée. Reconnectez-vous avant de modifier les chambres.",
    room_no_category: 'Aucune catégorie',
    room_inherited_price: 'Hérité de la catégorie',
    room_custom_price: 'Prix personnalisé',
    room_use_category_price: 'Utiliser le prix de la catégorie',
    room_floor_unknown: 'Étage non défini',
    room_capacity_unknown: 'Capacité non définie',
  },
}

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState('en')

  function toggleLanguage() {
    setLanguage((prev) => (prev === 'en' ? 'fr' : 'en'))
  }

  function t(key) {
    return translations[language][key] || key
  }

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}
