import { useState } from 'react'
import { LanguageContext } from './language-context'

const translations = {
  en: {
    header_title: 'Dashboard',
    switch_language: 'Switch language',
    notifications: 'Notifications',
    settings: 'Settings',
    logout: 'Log out',
    staff_account: 'Staff account',
    nav_dashboard: 'Dashboard',
    nav_rooms: 'Rooms',
    nav_categories: 'Categories',
    nav_customers: 'Customers',
    customers_title: 'Customers',
    customers_subtitle: 'Manage your guest list, contact details, and client records in one place.',
    customers_add: 'Add customer',
    customers_total: 'Total customers',
    customers_with_email: 'With email',
    customers_with_phone: 'With phone',
    customers_with_id: 'With ID',
    customers_search_placeholder: 'Search customer by name, phone, email, or ID',
    customers_filter_all: 'All customers',
    customers_filter_email: 'Has email',
    customers_filter_phone: 'Has phone',
    customers_filter_id: 'Has identification',
    customers_no_results_title: 'No customers found',
    customers_no_results_text: 'Try another search term or create a new customer profile.',
    customer_form_create_title: 'New customer',
    customer_form_edit_title: 'Edit customer',
    customer_form_create_subtitle: 'Create a detailed profile for a new guest or regular client.',
    customer_form_edit_subtitle: 'Update the client profile and contact details.',
    customer_name_label: 'Full name',
    customer_name_placeholder: 'Amara Diop',
    customer_phone_label: 'Phone',
    customer_phone_placeholder: '+221 77 123 4567',
    customer_email_label: 'Email',
    customer_email_placeholder: 'guest@example.com',
    customer_identification_label: 'Identification',
    customer_identification_placeholder: 'ID-1001',
    customer_address_label: 'Address',
    customer_address_placeholder: 'Route de Ouakam, Dakar',
    customer_name_required: 'Customer name is required.',
    customer_email_invalid: 'Please enter a valid email address.',
    customer_create: 'Create customer',
    customer_save: 'Save customer',
    customer_cancel: 'Cancel',
    customer_edit: 'Edit',
    customer_delete: 'Delete',
    customer_create_success: 'Customer created.',
    customer_update_success: 'Customer updated.',
    customer_delete_success: 'Customer deleted.',
    customer_error_title: 'Unable to load customers',
    customer_loading: 'Loading customers...',
    customer_retry: 'Retry',
    customer_auth_required: 'Your session is not authenticated. Log in again before changing customers.',
    customer_delete_confirm_message: 'Delete this customer profile?',
    customer_table_name: 'Customer',
    customer_table_contact: 'Contact',
    customer_table_identification: 'Identification',
    customer_table_address: 'Address',
    customer_table_actions: 'Actions',
    customer_table_no_id: 'No ID provided',
    customer_table_no_address: 'No address provided',
    nav_reservations: 'Reservations',
    reservations_title: 'Reservations',
    reservations_subtitle: 'Manage guest stays, date ranges, room assignment, and booking lifecycle from one place.',
    reservations_add: 'Add reservation',
    reservations_total: 'Total reservations',
    reservation_stat_active: 'Active',
    reservation_stat_completed: 'Completed',
    reservation_stat_cancelled: 'Cancelled',
    reservations_search_placeholder: 'Search by customer, room, or status',
    reservations_no_results_title: 'No reservations found',
    reservations_no_results_text: 'Use a different search term or create a new reservation.',
    reservation_form_create_title: 'New reservation',
    reservation_form_edit_title: 'Edit reservation',
    reservation_customer_label: 'Customer',
    reservation_customer_placeholder: 'Select customer',
    reservation_room_label: 'Room',
    reservation_room_placeholder: 'Select room',
    reservation_start_label: 'Start date',
    reservation_end_label: 'End date',
    reservation_amount_label: 'Amount',
    reservation_status_label: 'Status',
    reservation_client_required: 'Please select a customer.',
    reservation_room_required: 'Please select a room.',
    reservation_dates_required: 'Start and end dates are required.',
    reservation_dates_invalid: 'The end date must be after the start date.',
    reservation_amount_invalid: 'Amount must be zero or greater.',
    reservation_create: 'Create reservation',
    reservation_save: 'Save reservation',
    reservation_cancel: 'Cancel',
    reservation_loading: 'Saving...',
    reservation_create_success: 'Reservation created.',
    reservation_update_success: 'Reservation updated.',
    reservation_checkin_success: 'Reservation checked in.',
    reservation_checkout_success: 'Reservation checked out.',
    reservation_cancel_success: 'Reservation cancelled.',
    reservation_extend_success: 'Reservation extended.',
    reservation_extend_prompt: 'Choose the new end date (YYYY-MM-DD)',
    reservation_overlap_error: 'This room is not available for the selected dates.',
    reservation_auth_required: 'Your session is not authenticated. Log in again before changing reservations.',
    reservation_error_title: 'Unable to load reservations',
    reservation_retry: 'Retry',
    reservation_status_active: 'Active',
    reservation_status_completed: 'Completed',
    reservation_status_cancelled: 'Cancelled',
    reservation_filter_all: 'All statuses',
    reservation_table_customer: 'Customer',
    reservation_table_room: 'Room',
    reservation_table_dates: 'Dates',
    reservation_table_amount: 'Amount',
    reservation_table_status: 'Status',
    reservation_table_actions: 'Actions',
    reservation_edit: 'Edit',
    reservation_checkin: 'Check in',
    reservation_checkout: 'Check out',
    reservation_extend: 'Extend',
    reservation_history: 'History',
    reservation_history_title: 'Reservation history',
    reservation_history_empty: 'No history recorded',
    reservation_history_empty_text: 'This customer-room pairing has no prior reservations yet.',
    reservation_unknown_customer: 'Unknown customer',
    reservation_unknown_room: 'Unknown room',
    nav_payments: 'Payments',
    nav_payments: 'Payments',
    notif_checkout_soon: 'Room 12 checkout due in 2 hours',
    notif_maintenance_done: 'Room 5 maintenance completed',
    notif_payment_received: 'Payment received for Reservation #204',
    welcome_back: 'Welcome back',
    dashboard_subtitle: "Here's what's happening across your property today.",
    stat_available: 'Available',
    stat_reserved: 'Reserved',
    stat_occupied: 'Occupied',
    stat_maintenance: 'Maintenance',
    stat_out_of_service: 'Out of Service',
    recent_reservations: 'Recent Reservations',
    quick_actions: 'Quick Actions',
    action_new_reservation: 'New Reservation',
    action_add_room: 'Add Room',
    action_add_customer: 'Add Customer',
    categories_title: 'Categories',
    categories_subtitle: 'Manage room categories, prices, and room assignments.',
    categories_add: 'Add category',
    categories_add_defaults: 'Add default categories',
    categories_total: 'Categories',
    categories_assigned_rooms: 'Assigned rooms',
    categories_default_price: 'Default price',
    categories_room: 'room',
    categories_rooms: 'rooms',
    categories_empty_title: 'No categories yet',
    categories_empty_text: 'Start with the five standard room categories or create a custom one.',
    categories_no_description: 'No description provided.',
    category_form_create_title: 'New category',
    category_form_edit_title: 'Edit category',
    category_name_label: 'English name',
    category_name_placeholder: 'Furnished apartment',
    category_description_label: 'English description',
    category_description_placeholder: 'Short description for this category',
    category_price_label: 'Default price',
    category_price_hint: 'Rooms inherit this price unless their price is changed explicitly.',
    category_create: 'Create category',
    category_save: 'Save category',
    category_cancel: 'Cancel',
    category_edit: 'Edit',
    category_delete: 'Delete',
    category_delete_title: 'Delete category',
    category_delete_intro: 'This action cannot be undone.',
    category_delete_confirm: 'Delete category',
    category_delete_blocked: 'This category contains rooms. Move or delete those rooms before deleting the category.',
    category_name_required: 'Category name is required.',
    category_loading: 'Loading categories...',
    category_error_title: 'Unable to load categories',
    category_seed_success: 'Default categories added.',
    category_seed_none: 'Default categories already exist.',
    category_create_success: 'Category created.',
    category_update_success: 'Category updated.',
    category_delete_success: 'Category deleted.',
    category_auth_required: 'Your session is not authenticated. Log in again before changing categories.',
    rooms_title: 'Rooms',
    rooms_subtitle: 'Manage building units, category pricing, availability, and operational status.',
    rooms_add: 'Add room',
    rooms_add_test: 'Add test rooms',
    rooms_total: 'Total rooms',
    rooms_available: 'Available',
    rooms_active: 'Reserved / occupied',
    rooms_attention: 'Needs attention',
    rooms_search_placeholder: 'Search room number, category, or description',
    rooms_filter_all_statuses: 'All statuses',
    rooms_filter_all_categories: 'All categories',
    rooms_no_results_title: 'No rooms found',
    rooms_no_results_text: 'Adjust your filters or create a new room.',
    rooms_empty_title: 'No rooms yet',
    rooms_empty_text: 'Create categories first, then register each room with its floor, capacity, price, and status.',
    rooms_missing_categories: 'Create at least one category before adding rooms.',
    room_form_create_title: 'New room',
    room_form_edit_title: 'Edit room',
    room_number_label: 'Room number',
    room_number_placeholder: 'A12 or 204',
    room_category_label: 'Category',
    room_description_label: 'Description',
    room_description_placeholder: 'Optional notes: balcony, private bathroom, repairs...',
    room_floor_label: 'Floor',
    room_floor_short: 'Floor',
    room_capacity_label: 'Capacity',
    room_capacity_unit: 'people',
    room_price_label: 'Price',
    room_status_label: 'Status',
    room_create: 'Create room',
    room_save: 'Save room',
    room_cancel: 'Cancel',
    room_edit: 'Edit',
    room_delete: 'Delete',
    room_delete_title: 'Delete room',
    room_delete_intro: 'This action cannot be undone.',
    room_delete_safety_note: 'If this room has reservation history, deletion will be blocked to protect business records.',
    room_delete_confirm: 'Delete room',
    room_delete_blocked: 'This room has reservation history. It cannot be deleted.',
    room_number_required: 'Room number is required.',
    room_category_required: 'Category is required.',
    room_price_invalid: 'Price must be zero or greater.',
    room_duplicate_number: 'A room with this number already exists.',
    room_loading: 'Loading rooms...',
    room_error_title: 'Unable to load rooms',
    room_create_success: 'Room created.',
    room_update_success: 'Room updated.',
    room_delete_success: 'Room deleted.',
    room_seed_success: 'Test rooms added.',
    room_seed_none: 'Test rooms already exist.',
    room_auth_required: 'Your session is not authenticated. Log in again before changing rooms.',
    room_no_category: 'No category',
    room_inherited_price: 'Inherited from category',
    room_custom_price: 'Custom room price',
    room_use_category_price: 'Use category price',
    room_floor_unknown: 'Floor not set',
    room_capacity_unknown: 'Capacity not set',
  },
  fr: {
    header_title: 'Tableau de bord',
    switch_language: 'Changer de langue',
    notifications: 'Notifications',
    settings: 'Paramètres',
    logout: 'Déconnexion',
    staff_account: 'Compte du personnel',
    nav_dashboard: 'Tableau de bord',
    nav_rooms: 'Chambres',
    nav_categories: 'Catégories',
    nav_customers: 'Clients',
    customers_title: 'Clients',
    customers_subtitle: 'Gérez votre liste d’invités, les coordonnées et les dossiers clients en un seul endroit.',
    customers_add: 'Ajouter un client',
    customers_total: 'Total clients',
    customers_with_email: 'Avec email',
    customers_with_phone: 'Avec téléphone',
    customers_with_id: 'Avec identifiant',
    customers_search_placeholder: 'Rechercher un client par nom, téléphone, email ou identifiant',
    customers_filter_all: 'Tous les clients',
    customers_filter_email: 'A un email',
    customers_filter_phone: 'A un téléphone',
    customers_filter_id: 'A une pièce d’identité',
    customers_no_results_title: 'Aucun client trouvé',
    customers_no_results_text: 'Essayez un autre terme de recherche ou créez un nouveau profil client.',
    customer_form_create_title: 'Nouveau client',
    customer_form_edit_title: 'Modifier le client',
    customer_form_create_subtitle: 'Créez un profil détaillé pour un nouvel invité ou un client régulier.',
    customer_form_edit_subtitle: 'Mettez à jour le profil du client et ses coordonnées.',
    customer_name_label: 'Nom complet',
    customer_name_placeholder: 'Amara Diop',
    customer_phone_label: 'Téléphone',
    customer_phone_placeholder: '+221 77 123 4567',
    customer_email_label: 'Email',
    customer_email_placeholder: 'invite@example.com',
    customer_identification_label: 'Pièce d’identité',
    customer_identification_placeholder: 'ID-1001',
    customer_address_label: 'Adresse',
    customer_address_placeholder: 'Route de Ouakam, Dakar',
    customer_name_required: 'Le nom du client est obligatoire.',
    customer_email_invalid: 'Veuillez saisir une adresse email valide.',
    customer_create: 'Créer le client',
    customer_save: 'Enregistrer le client',
    customer_cancel: 'Annuler',
    customer_edit: 'Modifier',
    customer_delete: 'Supprimer',
    customer_create_success: 'Client créé.',
    customer_update_success: 'Client mis à jour.',
    customer_delete_success: 'Client supprimé.',
    customer_error_title: 'Impossible de charger les clients',
    customer_loading: 'Chargement des clients...',
    customer_retry: 'Réessayer',
    customer_auth_required: "Votre session n'est pas authentifiée. Reconnectez-vous avant de modifier les clients.",
    customer_delete_confirm_message: 'Supprimer ce profil client ?',
    customer_table_name: 'Client',
    customer_table_contact: 'Contact',
    customer_table_identification: 'Pièce d’identité',
    customer_table_address: 'Adresse',
    customer_table_actions: 'Actions',
    customer_table_no_id: 'Aucune pièce d’identité',
    customer_table_no_address: 'Aucune adresse renseignée',
    nav_reservations: 'Réservations',
    reservations_title: 'Réservations',
    reservations_subtitle: 'Gérez les séjours des clients, les plages de dates, l’affectation des chambres et tout le cycle de réservation depuis un seul endroit.',
    reservations_add: 'Ajouter une réservation',
    reservations_total: 'Total réservations',
    reservation_stat_active: 'Actives',
    reservation_stat_completed: 'Terminées',
    reservation_stat_cancelled: 'Annulées',
    reservations_search_placeholder: 'Rechercher par client, chambre ou statut',
    reservations_no_results_title: 'Aucune réservation trouvée',
    reservations_no_results_text: 'Essayez un autre terme de recherche ou créez une nouvelle réservation.',
    reservation_form_create_title: 'Nouvelle réservation',
    reservation_form_edit_title: 'Modifier la réservation',
    reservation_customer_label: 'Client',
    reservation_customer_placeholder: 'Sélectionner un client',
    reservation_room_label: 'Chambre',
    reservation_room_placeholder: 'Sélectionner une chambre',
    reservation_start_label: 'Date de début',
    reservation_end_label: 'Date de fin',
    reservation_amount_label: 'Montant',
    reservation_status_label: 'Statut',
    reservation_client_required: 'Veuillez sélectionner un client.',
    reservation_room_required: 'Veuillez sélectionner une chambre.',
    reservation_dates_required: 'Les dates de début et de fin sont obligatoires.',
    reservation_dates_invalid: 'La date de fin doit être postérieure à la date de début.',
    reservation_amount_invalid: 'Le montant doit être supérieur ou égal à zéro.',
    reservation_create: 'Créer la réservation',
    reservation_save: 'Enregistrer la réservation',
    reservation_cancel: 'Annuler',
    reservation_loading: 'Enregistrement...',
    reservation_create_success: 'Réservation créée.',
    reservation_update_success: 'Réservation mise à jour.',
    reservation_checkin_success: 'Réservation enregistrée.',
    reservation_checkout_success: 'Séjour clôturé.',
    reservation_cancel_success: 'Réservation annulée.',
    reservation_extend_success: 'Réservation prolongée.',
    reservation_extend_prompt: 'Choisissez la nouvelle date de fin (AAAA-MM-JJ)',
    reservation_overlap_error: 'Cette chambre n’est pas disponible pour les dates sélectionnées.',
    reservation_auth_required: "Votre session n'est pas authentifiée. Reconnectez-vous avant de modifier les réservations.",
    reservation_error_title: 'Impossible de charger les réservations',
    reservation_retry: 'Réessayer',
    reservation_status_active: 'Active',
    reservation_status_completed: 'Terminée',
    reservation_status_cancelled: 'Annulée',
    reservation_filter_all: 'Tous les statuts',
    reservation_table_customer: 'Client',
    reservation_table_room: 'Chambre',
    reservation_table_dates: 'Dates',
    reservation_table_amount: 'Montant',
    reservation_table_status: 'Statut',
    reservation_table_actions: 'Actions',
    reservation_edit: 'Modifier',
    reservation_checkin: 'Arrivée',
    reservation_checkout: 'Départ',
    reservation_extend: 'Prolonger',
    reservation_history: 'Historique',
    reservation_history_title: 'Historique des réservations',
    reservation_history_empty: 'Aucun historique enregistré',
    reservation_history_empty_text: 'Cette association client-chambre n’a pas encore d’historique.',
    reservation_unknown_customer: 'Client inconnu',
    reservation_unknown_room: 'Chambre inconnue',
    nav_payments: 'Paiements',
    nav_payments: 'Paiements',
    notif_checkout_soon: 'Chambre 12 : départ prévu dans 2 heures',
    notif_maintenance_done: 'Chambre 5 : entretien terminé',
    notif_payment_received: 'Paiement reçu pour la réservation #204',
    welcome_back: 'Bon retour',
    dashboard_subtitle: "Voici ce qui se passe dans votre établissement aujourd'hui.",
    stat_available: 'Disponibles',
    stat_reserved: 'Réservées',
    stat_occupied: 'Occupées',
    stat_maintenance: 'Entretien',
    stat_out_of_service: 'Hors service',
    recent_reservations: 'Réservations récentes',
    quick_actions: 'Actions rapides',
    action_new_reservation: 'Nouvelle réservation',
    action_add_room: 'Ajouter une chambre',
    action_add_customer: 'Ajouter un client',
    categories_title: 'Catégories',
    categories_subtitle: 'Gérez les catégories de chambres, les prix et les affectations.',
    categories_add: 'Ajouter une catégorie',
    categories_add_defaults: 'Ajouter les catégories par défaut',
    categories_total: 'Catégories',
    categories_assigned_rooms: 'Chambres affectées',
    categories_default_price: 'Prix par défaut',
    categories_room: 'chambre',
    categories_rooms: 'chambres',
    categories_empty_title: 'Aucune catégorie',
    categories_empty_text: 'Commencez avec les cinq catégories standards ou créez une catégorie personnalisée.',
    categories_no_description: 'Aucune description renseignée.',
    category_form_create_title: 'Nouvelle catégorie',
    category_form_edit_title: 'Modifier la catégorie',
    category_name_label: 'Nom français',
    category_name_placeholder: 'Appartement meublé',
    category_description_label: 'Description française',
    category_description_placeholder: 'Courte description de cette catégorie',
    category_price_label: 'Prix par défaut',
    category_price_hint: 'Les chambres héritent de ce prix sauf modification explicite.',
    category_create: 'Créer la catégorie',
    category_save: 'Enregistrer',
    category_cancel: 'Annuler',
    category_edit: 'Modifier',
    category_delete: 'Supprimer',
    category_delete_title: 'Supprimer la catégorie',
    category_delete_intro: 'Cette action est définitive.',
    category_delete_confirm: 'Supprimer la catégorie',
    category_delete_blocked: 'Cette catégorie contient des chambres. Déplacez ou supprimez ces chambres avant de supprimer la catégorie.',
    category_name_required: 'Le nom de la catégorie est obligatoire.',
    category_loading: 'Chargement des catégories...',
    category_error_title: 'Impossible de charger les catégories',
    category_seed_success: 'Catégories par défaut ajoutées.',
    category_seed_none: 'Les catégories par défaut existent déjà.',
    category_create_success: 'Catégorie créée.',
    category_update_success: 'Catégorie mise à jour.',
    category_delete_success: 'Catégorie supprimée.',
    category_auth_required: "Votre session n'est pas authentifiée. Reconnectez-vous avant de modifier les catégories.",
    rooms_title: 'Chambres',
    rooms_subtitle: "Gérez les unités du bâtiment, les prix par catégorie, la disponibilité et l'état opérationnel.",
    rooms_add: 'Ajouter une chambre',
    rooms_add_test: 'Ajouter des chambres test',
    rooms_total: 'Total chambres',
    rooms_available: 'Disponibles',
    rooms_active: 'Réservées / occupées',
    rooms_attention: 'À surveiller',
    rooms_search_placeholder: 'Rechercher par numéro, catégorie ou description',
    rooms_filter_all_statuses: 'Tous les statuts',
    rooms_filter_all_categories: 'Toutes les catégories',
    rooms_no_results_title: 'Aucune chambre trouvée',
    rooms_no_results_text: 'Ajustez vos filtres ou créez une nouvelle chambre.',
    rooms_empty_title: 'Aucune chambre',
    rooms_empty_text: "Créez d'abord les catégories, puis enregistrez chaque chambre avec son étage, sa capacité, son prix et son statut.",
    rooms_missing_categories: "Créez au moins une catégorie avant d'ajouter des chambres.",
    room_form_create_title: 'Nouvelle chambre',
    room_form_edit_title: 'Modifier la chambre',
    room_number_label: 'Numéro de chambre',
    room_number_placeholder: 'A12 ou 204',
    room_category_label: 'Catégorie',
    room_description_label: 'Description',
    room_description_placeholder: 'Notes optionnelles : balcon, douche privée, réparations...',
    room_floor_label: 'Étage',
    room_floor_short: 'Étage',
    room_capacity_label: 'Capacité',
    room_capacity_unit: 'personnes',
    room_price_label: 'Prix',
    room_status_label: 'Statut',
    room_create: 'Créer la chambre',
    room_save: 'Enregistrer',
    room_cancel: 'Annuler',
    room_edit: 'Modifier',
    room_delete: 'Supprimer',
    room_delete_title: 'Supprimer la chambre',
    room_delete_intro: 'Cette action est définitive.',
    room_delete_safety_note: "Si cette chambre possède un historique de réservation, la suppression sera bloquée afin de protéger les données métier.",
    room_delete_confirm: 'Supprimer la chambre',
    room_delete_blocked: 'Cette chambre possède un historique de réservation. Elle ne peut pas être supprimée.',
    room_number_required: 'Le numéro de chambre est obligatoire.',
    room_category_required: 'La catégorie est obligatoire.',
    room_price_invalid: 'Le prix doit être supérieur ou égal à zéro.',
    room_duplicate_number: 'Une chambre avec ce numéro existe déjà.',
    room_loading: 'Chargement des chambres...',
    room_error_title: 'Impossible de charger les chambres',
    room_create_success: 'Chambre créée.',
    room_update_success: 'Chambre mise à jour.',
    room_delete_success: 'Chambre supprimée.',
    room_seed_success: 'Chambres test ajoutées.',
    room_seed_none: 'Les chambres test existent déjà.',
    room_auth_required: "Votre session n'est pas authentifiée. Reconnectez-vous avant de modifier les chambres.",
    room_no_category: 'Aucune catégorie',
    room_inherited_price: 'Hérité de la catégorie',
    room_custom_price: 'Prix personnalisé',
    room_use_category_price: 'Utiliser le prix de la catégorie',
    room_floor_unknown: 'Étage non défini',
    room_capacity_unknown: 'Capacité non définie',
  },
}

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState('en')

  function toggleLanguage() {
    setLanguage((prev) => (prev === 'en' ? 'fr' : 'en'))
  }

  function t(key) {
    return translations[language][key] || key
  }

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}
